# automatically invite contributors to this particular team in the organization when their pull-requests
# are merged which grants them the ability to help with triaging (labeling) github issues and enables
# maintainers to assign issues to these individuals.
team: unoplatform/community
